USE master
GO
 
CREATE LOGIN DVDLibraryApp WITH PASSWORD='testing123'
GO

USE DVDLibrary
GO
 
CREATE USER DVDLibraryApp FOR LOGIN DVDLibraryApp
GO

GRANT EXECUTE ON CreateDVD TO DVDLibraryApp
GRANT EXECUTE ON DeleteDVD TO DVDLibraryApp
GRANT EXECUTE ON ReadDVD TO DVDLibraryApp
GRANT EXECUTE ON ReadDVDDirector TO DVDLibraryApp
GRANT EXECUTE ON ReadDVDList TO DVDLibraryApp
GRANT EXECUTE ON ReadDVDRating TO DVDLibraryApp
GRANT EXECUTE ON ReadDVDTitle TO DVDLibraryApp
GRANT EXECUTE ON ReadDVDYear TO DVDLibraryApp
GRANT EXECUTE ON UpdateDVD TO DVDLibraryApp

GO

GRANT SELECT ON DVDs TO DVDLibraryApp
GRANT INSERT ON DVDs TO DVDLibraryApp
GRANT UPDATE ON DVDs TO DVDLibraryApp
GRANT DELETE ON DVDs TO DVDLibraryApp
GO